---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart application service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
