---
common_packages:
  - nginx
  - curl
  - acl
  - logrotate
  - ufw

kijanikiosk_group: kijanikiosk

base_dir: /opt/kijanikiosk
config_dir: /opt/kijanikiosk/config
log_dir: /var/log/kijanikiosk
health_dir: /opt/kijanikiosk/health

journald_max_use: 500M

firewall_allowed_ports:
  - "22"
  - "80"
  - "443"
  - "3000"
  - "3001"
